name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Semantic versioning tag (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  call-production-workflow:
    uses: ./.github/workflows/deploy-to-prod.yaml
    with:
      version: ${{ github.event.inputs.tag }}
    secrets: inherit
